language: node_js
sudo: required
os:
  - linux
  - osx
node_js:
  - "10.9.0"

services:
  - xvfb

addons:
  chrome: stable

script:
- travis_retry npm install --depth 0 --silent
- travis_retry npm run test:node
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( travis_retry npm run test:browser ) fi
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( travis_retry npm run test:e2e:travis ) fi
- travis_retry npm run test:performance
- npm run build
- npm run lint
- npm run test:typings
- npm run size:webpack
- npm run size:browserify
