language: node_js
sudo:            required
os:
  - linux
node_js:
  - "10.6.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
- travis_retry npm install --depth 0 --silent
- npm run lint
- npm run build
- travis_retry npm run test:node
- travis_retry npm run test:browser
- travis_retry npm run test:e2e
- travis_retry npm run test:performance
- npm run test:typings
- npm run size:webpack
- npm run size:browserify