language: node_js
sudo: required
cache: false
os:
  - linux
  - osx
node_js:
  - "12.7.0"

services:
  - xvfb

addons:
  chrome: stable
  firefox: latest

script:
- travis_retry npm install --depth 0 --silent
- npm run build
- travis_retry npm run test:node
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( travis_retry npm run test:browser ) fi
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( sleep 10 && travis_retry npm run test:e2e:travis ) fi
- travis_retry npm run test:performance
- npm run lint
- npm run test:typings
- npm run size:webpack
- npm run size:browserify
- npm run size:rollup