language: node_js
sudo: required
os:
  - linux
  - osx
node_js:
  - "10.9.0"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0;
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 3 # give xvfb some time to start


stages:
  - install
  - build
  - format
  - size
  - tests

jobs:
  include:
    - stage: install
      script: travis_retry npm install --depth 0 --silent

    - stage: build
      script: npm run build

    - stage: format
      script: travis_retry npm run lint
      env: LABEL=format:lint
    - stage: format
      script: npm run test:typings
      env: LABEL=format:typings

    - stage: size
      script: npm run size:webpack
      env: LABEL=size:webpack
    - stage: size
      script: npm run size:browserify
      env: LABEL=size:browserify

    - stage: tests
      script: travis_retry npm run test:node
      env: LABEL=test:node
    - stage: tests
      os: linux
      script: if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( travis_retry npm run test:browser ) fi
      env: LABEL=test:browser
    - stage: tests
      os: linux
      script: if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ( travis_retry npm run test:e2e:travis ) fi
      env: LABEL=test:e2e
    - stage: tests
      script: travis_retry npm run test:performance
      env: LABEL=test:performance
